[package]
name = "pretable"
version = "0.3.2"
authors = ["ryota-sakamoto <sakamo.ryota+github@gmail.com>"]
repository = "https://github.com/ryota-sakamoto/pretable"
keywords = ["table", "pretty"]
license-file = "LICENSE"
description = "show pretty table"

[dependencies]
